# Uncomment the next line to define a global platform for your project
platform :ios, '12.1'

target 'Eight' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Eight

  target 'EightTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'EightUITests' do
    inherit! :search_paths
    # Pods for testing
  end

pod 'Firebase/Core'
pod 'Firebase/Database'
pod 'Firebase/Auth'

end
